### PR TITLE
feat: add api service for requesting user by id

### PR DESCRIPTION
**Pull request by duongthienlee**
Details: user can be now search by using id.
Add some Postman tests case

### CODE REVIEW

**Comment by duongthienlee** [comment]
> Is this still working with the current version of the back-end?
We can check whether we can merge this branch into master, if there is no conflict, means we are ok with this

**Comment by duongthienlee** [comment]
just test it locally, it can be totally merge with master branch, since there is no conflict. Basically if no one has recently made any changes to those files that I had changes, Even though they merge the pull request before this request, as long as there is no conflict between those files, it's ok to merge.
GitHub will tell you whether there is a conflict when merging between branches, if there is conflict, you can still merge it locally by fixing it locally.

**Comment by BlerimPlakolli** [comment]
Maybe is good to do some checks for id to be sure that the id is a number before sending request to the db, so if the id is not a number to stop request in the backend.

**Comment by duongthienlee** [comment]
> Maybe is good to do some checks for id to be sure that the id is a number before sending request to the db, so if the id is not a number to stop request in the backend.

Yes, that may be a good idea if we indeed want to get the user info by entering raw id. However, I don't think that's the case here, because from the front-end repo. I see there is a UserDetailsView component that will display user info based on params id. So I think in this case, when we click a user row which will have it own id in Users view, it will send get request based on that id. So, basically the id is always a number that already received from the API.

**Comment by duongthienlee** [comment]
So far, after implemented the user view on the front end part, I think we might not need this API service for requesting user by id. I don't see any usage for this, don't even know why I have implemented this API service. I will close this pull request.
Since we're going to have UserDetailsView, so I can add some PUT API service to update user info.

**Pull request closed without merging**
